package GUI;

import Dominio.*;
import Eccezioni.*;

import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;

public class SignInFrame extends javax.swing.JFrame {

    private final FitnessReady FR;
    /**
     * Creates new form SignInFrame
     */
    public SignInFrame() {
        FR = FitnessReady.getInstance();
        initComponents();
    }
    
    private void close(){
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistrazione = new javax.swing.JPanel();
        labelRegistrazione = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCognome = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelConfermaPassword = new javax.swing.JLabel();
        labelAltezza = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelMetri = new javax.swing.JLabel();
        labelChili = new javax.swing.JLabel();
        labelObiettivo = new javax.swing.JLabel();
        labelAvvisoRegistrazione1 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        textFieldCognome = new javax.swing.JTextField();
        texteFieldEmail = new javax.swing.JTextField();
        textFieldAltezza = new javax.swing.JTextField();
        textFieldPeso = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        fieldConfermaPassword = new javax.swing.JPasswordField();
        buttonSubmit = new javax.swing.JButton();
        radioButtonDefinizione = new javax.swing.JRadioButton();
        radioButtonAumento = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelRegistrazione.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRegistrazione.setText("Registrazione Utente");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNome.setText("Nome:");

        labelCognome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCognome.setText("Cognome:");

        labelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEmail.setText("E-mail:");

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPassword.setText("Password:");

        labelConfermaPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelConfermaPassword.setText("Conferma Password:");

        labelAltezza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAltezza.setText("Altezza:");

        labelPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPeso.setText("Peso:");

        labelMetri.setText("m  (*)");

        labelChili.setText("Kg (*)");

        labelObiettivo.setText("Obiettivo:");

        labelAvvisoRegistrazione1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAvvisoRegistrazione1.setText("(*) usare il punto \".\" e non la virgola \",\"");

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        radioButtonDefinizione.setText("Definizione massa muscolare");
        radioButtonDefinizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDefinizioneActionPerformed(evt);
            }
        });

        radioButtonAumento.setText("Aumento massa muscolare");
        radioButtonAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrazioneLayout = new javax.swing.GroupLayout(panelRegistrazione);
        panelRegistrazione.setLayout(panelRegistrazioneLayout);
        panelRegistrazioneLayout.setHorizontalGroup(
            panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(buttonSubmit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrazioneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegistrazione)
                .addGap(170, 170, 170))
            .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCognome)
                                .addComponent(labelPassword)
                                .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAltezza)
                            .addComponent(labelConfermaPassword))
                        .addComponent(labelPeso, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelObiettivo))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonAumento)
                    .addComponent(radioButtonDefinizione)
                    .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldCognome, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(texteFieldEmail)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldConfermaPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldPassword)
                        .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                            .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldAltezza)
                                .addComponent(textFieldPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrazioneLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(labelAvvisoRegistrazione1))
                                .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                                    .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelMetri)
                                        .addComponent(labelChili))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelRegistrazioneLayout.setVerticalGroup(
            panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelRegistrazione)
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCognome)
                    .addComponent(textFieldCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(texteFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfermaPassword)
                    .addComponent(fieldConfermaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAltezza)
                    .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMetri)
                        .addComponent(textFieldAltezza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPeso)
                            .addComponent(labelChili)
                            .addComponent(textFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegistrazioneLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelAvvisoRegistrazione1)))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonDefinizione)
                    .addComponent(labelObiettivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonAumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistrazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistrazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        String nome, cognome, email, password, confermaPassword, altezza, peso, obiettivo = "";
        
        try{
            nome = textFieldNome.getText();
            cognome = textFieldCognome.getText();
            email = texteFieldEmail.getText().toLowerCase();
            password = String.valueOf(fieldPassword.getPassword());
            confermaPassword = String.valueOf(fieldConfermaPassword.getPassword());
            altezza = textFieldAltezza.getText();
            peso = textFieldPeso.getText();
            if(radioButtonDefinizione.isSelected())
                obiettivo = "Definizione";
            else if(radioButtonAumento.isSelected())
                obiettivo = "Aumento";
            
            FR.registraCliente(nome, cognome, email, password, confermaPassword, altezza, peso, obiettivo);
            
            JOptionPane.showMessageDialog(this, "Registrazione effettuata");
            new LoginFrame().setVisible(true);
            close();
        }catch(NotPositiveNumberException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "'Altezza' e 'Peso' devono essere numeri positivi", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch(ExistingEmailException | PasswordNotEqualsException | EmptyFieldException e){
            JOptionPane.showMessageDialog(this, e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void radioButtonDefinizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDefinizioneActionPerformed
        if(radioButtonDefinizione.isSelected())
            radioButtonAumento.setSelected(false);
    }//GEN-LAST:event_radioButtonDefinizioneActionPerformed

    private void radioButtonAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAumentoActionPerformed
        if(radioButtonAumento.isSelected())
            radioButtonDefinizione.setSelected(false);
    }//GEN-LAST:event_radioButtonAumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JPasswordField fieldConfermaPassword;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel labelAltezza;
    private javax.swing.JLabel labelAvvisoRegistrazione1;
    private javax.swing.JLabel labelChili;
    private javax.swing.JLabel labelCognome;
    private javax.swing.JLabel labelConfermaPassword;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelMetri;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelObiettivo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelRegistrazione;
    private javax.swing.JPanel panelRegistrazione;
    private javax.swing.JRadioButton radioButtonAumento;
    private javax.swing.JRadioButton radioButtonDefinizione;
    private javax.swing.JTextField textFieldAltezza;
    private javax.swing.JTextField textFieldCognome;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldPeso;
    private javax.swing.JTextField texteFieldEmail;
    // End of variables declaration//GEN-END:variables
}
