package GUI;

import Dominio.*;

import java.util.*;
import javax.swing.*;

public class TimerFrame extends javax.swing.JFrame {

    private FitnessReady FR;
    private TimerFrame TF = this;
    private final List<Esercizio> listaEsercizi;
    private Esercizio esercizio;
    private int i = 0;
    
    private static int milliseconds = 0;
    private static int seconds = 0;
    private static int minutes = 0;
    private static boolean state = true;
    /**
     * Creates new form TimerFrame
     */
    public TimerFrame() {
        FR = FitnessReady.getInstance();
        String email = FR.getClienteAttuale().getEmail();
        listaEsercizi = FR.getGestoreSchede().getSchedaCliente(email).getPianoEsercizi().getListaEsercizi();
        //Per riprendere eventualmente dagli esercizi non eseguiti
        for(int k = 0; k < listaEsercizi.size(); k++){
            if(listaEsercizi.get(k).getStato().equals("ESEGUITO"))
                i++;
        }
        esercizio = listaEsercizi.get(i);
        
        initComponents();
        
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        labelNome.setText(esercizio.getNome());
        labelMinutiDurata.setText(String.valueOf(esercizio.getDurata()));
        buttonNext.setEnabled(false);
    }
    
    private void close(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelDurata = new javax.swing.JLabel();
        labelMinuti = new javax.swing.JLabel();
        labelMinutiDurata = new javax.swing.JLabel();
        labelMinute = new javax.swing.JLabel();
        labelSecond = new javax.swing.JLabel();
        labelMillisecond = new javax.swing.JLabel();
        labelMin = new javax.swing.JLabel();
        labelSec = new javax.swing.JLabel();
        labelMillisec = new javax.swing.JLabel();
        labelGuida = new javax.swing.JLabel();
        labelStart = new javax.swing.JLabel();
        labelStop = new javax.swing.JLabel();
        labelReset = new javax.swing.JLabel();
        labelNext = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNome.setText("Nome Esercizio");

        labelDurata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDurata.setText("Durata:");

        labelMinuti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMinuti.setText("minuti");

        labelMinutiDurata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMinutiDurata.setText("0");

        labelMinute.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelMinute.setText("00 :");

        labelSecond.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelSecond.setText("00 :");

        labelMillisecond.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelMillisecond.setText("00");

        labelMin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelMin.setText("Min");

        labelSec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelSec.setText("Sec");

        labelMillisec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelMillisec.setText("Millisec");

        labelGuida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelGuida.setText("GUIDA:");

        labelStart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStart.setText("\"Start\" -> Avvia/Riprendi esercizio");

        labelStop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStop.setText("\"Stop\" -> Pausa esercizio");

        labelReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelReset.setText("\"Reset\" -> Ricomincia esercizio");

        labelNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNext.setText("\"Next\" -> Prossimo esercizio (Attivo a fine di ogni esercizio)");

        buttonStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonStop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonStop.setText("Stop");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("\"Close\" -> Chiudi/Concludi esecuzione esercizi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(labelMinute)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelMin)
                                        .addGap(34, 34, 34)
                                        .addComponent(labelSecond)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelSec)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelDurata)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelMinutiDurata))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelMillisecond)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelMillisec)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMinuti))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelGuida))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelStart))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelStop))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelReset))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNext))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelDurata)
                    .addComponent(labelMinuti)
                    .addComponent(labelMinutiDurata))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMillisecond)
                    .addComponent(labelMinute)
                    .addComponent(labelSecond)
                    .addComponent(labelMin)
                    .addComponent(labelSec)
                    .addComponent(labelMillisec))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGuida)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        state = true;
        
        buttonStart.setEnabled(false);
        Thread t = new Thread(){
            @Override
            public void run(){
                for(;;)
                    if(state == true)
                        try{
                            sleep(1);
                            if(milliseconds >= 1000){
                                milliseconds = 0;
                                seconds++;
                            }
                            if(seconds >= 60){
                                milliseconds = 0;
                                seconds = 0;
                                minutes++;
                            }
                            labelMillisecond.setText(" : " + milliseconds);
                            milliseconds++;
                            labelSecond.setText(" : " + seconds);
                            labelMinute.setText(" : " + minutes);
                            if(seconds == esercizio.getDurata()){
                                state = false;
                                FR.eseguiEsercizio(i);
                                if(i == listaEsercizi.size() - 1){
                                    JOptionPane.showMessageDialog(TF, "Piano Esercizi Completato!");
                                    close();
                                }
                                else{
                                    buttonStart.setEnabled(false);
                                    buttonNext.setEnabled(true);
                                }
                            }
                        }catch(InterruptedException e){}
                    else
                        break;
            }
        };
        t.start();
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        state = false;
        buttonStart.setEnabled(true);
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        state = false;
        
        minutes = 0;
        seconds = 0;
        milliseconds = 0;
        
        labelMinute.setText("00 : ");
        labelSecond.setText("00 : ");
        labelMillisecond.setText("00");
        
        buttonStart.setEnabled(true);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        if(i == listaEsercizi.size() - 1){
            JOptionPane.showMessageDialog(TF, "Piano Esercizi Completato!");
            close();
        }
        i++;
        esercizio = listaEsercizi.get(i);
        labelNome.setText(esercizio.getNome());
        labelMinutiDurata.setText(String.valueOf(esercizio.getDurata()));
        buttonResetActionPerformed(null);
        buttonNext.setEnabled(false);
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        close();
    }//GEN-LAST:event_buttonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDurata;
    private javax.swing.JLabel labelGuida;
    private javax.swing.JLabel labelMillisec;
    private javax.swing.JLabel labelMillisecond;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelMinute;
    private javax.swing.JLabel labelMinuti;
    private javax.swing.JLabel labelMinutiDurata;
    private javax.swing.JLabel labelNext;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelReset;
    private javax.swing.JLabel labelSec;
    private javax.swing.JLabel labelSecond;
    private javax.swing.JLabel labelStart;
    private javax.swing.JLabel labelStop;
    // End of variables declaration//GEN-END:variables
}
